# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-LazyFactory
version:      0.02
version_from: lib/Class/LazyFactory.pm
installdirs:  site
requires:
    Carp:                          1
    Class::Inspector:              1.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
